### ISSUE TITLE
Investigate unit test frameworks

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#1]
- Think about what the csvwlib project needs to be able to get from a unit testing framework.
- Investigate the popular testing unit testing frameworks in python.
- Come up with a presentation/document listing the benefits and drawbacks of each tool.
- Make a recommendation as to which tool we should adopt in csvwlib.

Note since this issue hasn't been looked into, @robons has started using unittest in the existing projects.

**Comment by rossbowen** [comment]
Given [`numpy`](https://github.com/numpy/numpy/blob/main/pytest.ini), [`requests`](https://github.com/psf/requests/blob/master/pytest.ini) and [`pandas`](https://github.com/pandas-dev/pandas) use `pytest` (i.e., three large packages in incredibly wide use throughout the Python community make use of it), I would propose we follow the masses...
