### ISSUE TITLE
Move infojson loader into gss-utils

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#101]
It really belongs in gss-utils and shouldn't ever be used by any external users. It's configured specifically for us.

We'll also need to bring along the CLI designed in Issue #108 if it has already been done.

In order to do this, we're going to want to bring our unit-tests across to gss-utils. gss-utils doesn't have a unit testing framework. So we'll need to introduce that into gss-utils as part of this ticket. AND make sure pytest is run as part of the Jenkins pipeline.

- [ ] Once Issue #159 has been completed, we will need to bring those changes along with the info.json loader into gss-utils

**Comment by mikeAdamss** [comment]
sorry Rob missed the original ping for this somehow.

Broadly I don't see the harm in adding pytest though we might need a steer from Alex on his vision for gssutils. If its intended in any way as a wider use tool this kinda thing might need to be an optional dependency of some sort.

We might also need to move decoupling things/tidying up in gssutils up the priorities a bit, it has the potential to get really messy, really fast.

**Comment by mikeAdamss** [comment]
@ajtucker @rossbowen - if we're moving move things into gssutils (see above) I probably need a fair dose of time pretty soonish to decouple things and generally tidy up. Gonna be a lot easier to do before we starting adding.

**Comment by robons** [comment]
So we had a chat with @mikeAdamss in the DM/DE catchup this morning and we agreed that given the low level of integration we want to achieve, we don't need to do any immediate refactoring of gss-utils to accommodate our desired changes.

We will almost certainly have future discussions on how to refactor and improve gss-utils in due course, but we don't need to wait for those to begin this work.
