### ISSUE TITLE
User can set custom URIs

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvwlib#14]
Ability for the user to provide their own URIs (overwriting defaults should they so wish).

This is focused on purely existing dimensions, opposed to establishing new namespaces.

**Comment by rossbowen** [comment]
When a user wants to describe a dimension in their dataset, they are able to provide their own custom URI and the model will accept that.

e.g. user can provide `http://gss-data.org.uk/example/dimension/geography` and the model will populate the correct relevant information using that URI.
