### ISSUE TITLE
Spike - Investigate using Poetry instead of Pipenv

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#185]
We've been having some problems with pipenv:

* Slow to lock files
* relatively slow to sync files
* Doesn't give useful feedback when something goes wrong.
  * Which packages were in conflict?
  * What did you break when doing?

[Poetry](https://python-poetry.org/) is an alternative package/dependency manager for python packages. We need to see if it fits out requirements:

* Can cope with installing from git repos
* Is faster than pipenv when locking
* Gives more debuggable/comprehensible error messages when things go wrong.

If we find that it meets all of the above requirements, then we should create a task to replace pipenv with poetry within csvwlib - and start discussions about replacing it in gss-utils.

**Comment by canwaf** [comment]
```
(csvqb-FcQ3xPH5-py3.9) root@b48f208316d0:/workspaces/csvwlib/csvqb# poetry lock
Updating dependencies
Resolving dependencies... (14.7s)

  SolverProblemError

  Because csvqb depends on sharedmodels (0.1.0) which depends on rdflib (~=5.0.0), rdflib is required.
  So, because csvqb depends on rdflib (==4.2.2), version solving failed.

  at /usr/local/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
(csvqb-FcQ3xPH5-py3.9) root@b48f208316d0:/workspaces/csvwlib/csvqb# 
```

**Comment by canwaf** [comment]
- [ ] Figure out how to write out to `setup.py` to be able to use csvwlib in gss-utils.

**Comment by canwaf** [comment]
It doesn't look like we need a `setup.py` anymore [due to PEP 517 and PEP 518](https://snarky.ca/what-the-heck-is-pyproject-toml/).

**Comment by canwaf** [comment]
- [ ] Compare `pipenv-cascade.py` timing to `poetry-cascade.py`

**Comment by canwaf** [comment]
# poetry-cascasde.py timing
```
root@cc345a7c9e19:/workspaces/csvwlib# time ./poetry-cascade.sh 
====================== devtools
Updating dependencies
Resolving dependencies... (15.5s)

Writing lock file
====================== sharedmodels
Updating dependencies
Resolving dependencies... (2.2s)

Writing lock file
====================== pmd
Creating virtualenv pmd-F1Vt5to1-py3.9 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
====================== csvqb
Creating virtualenv csvqb-FcQ3xPH5-py3.9 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (26.5s)

Writing lock file
./poetry-cascade.sh: line 20: /root: Is a directory

real    0m50.633s
user    0m35.877s
sys     0m5.834s
```

**Comment by canwaf** [comment]
# How to convert from Pipenv to Poetry
Conversion is done using the tool at [pipenv-poetry-migrate](https://github.com/yhino/pipenv-poetry-migrate). 

1. `pip install poetry pipenv-poetry-migrate`
2. delete `pyproject.toml` from the directory if it exists
3. `poetry init` then follow walkthrough
4. `pipenv-poetry-migrate -f Pipfile -t pyproject.toml`
5. `poetry lock`
6. Delete `Pipfile`, `Pipfile.lock` and never look back

**Comment by canwaf** [comment]
- [ ] Confirm that a `pyproject.toml` is all that is required for a `pipenv`-based project to build this egg.

**Comment by canwaf** [comment]
# gss-utils pipenv vs poetry comparison
A poetry limitation was discovered when converting gss-utils from pipenv, that there is no support for a git package referenced with a subdirectory. The comments on poetry's GitHub is that there is no PEP on this matter. The work around used to make this comparison was installing devtools (i.e. csvwlib's `infojson2csvqb` package) using a wheel referenced using a url.

Results are pipenv 4m51.181s vs poetry 0m42.130s.

## pipenv lock of gss-utils
```
root@232e8f6846d3:/workspaces/gss-utils# time pipenv lock --dev --pre
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (b9a07b)!

real    5m32.600s
user    4m51.181s
sys     1m40.962s
```

## poetry lock of gss-utils
```
root@232e8f6846d3:/workspaces/gss-utils# time poetry lock
Updating dependencies
Resolving dependencies... (59.6s)

Writing lock file

real    1m1.190s
user    0m42.130s
sys     0m5.341s
```

**Comment by canwaf** [comment]
# Behavioural differences
Poetry does behave a bit differently, and so your development practises need to change...
1. Your local package you're working on is always installed and always editable - so don't include it in your `pyproject.toml` otherwise you'll get an AssertError. (If you don't want to install the root directory you need to specify `--no-root` in your `poetry install`
2. By default poetry installs the dev packages, to suppress this use the `--no-dev` flag.
