### ISSUE TITLE
Map scrapers to new common model

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvwlib#28]
We could output a nice scraper.json file containing the metadata from this process -> feed into CLI which takes {info.json, scraper.json (optional) and the tidy-csv.csv} and outputs the CSV-W. 

We probably want this functionality to output a `scraper.json` file which is fed into the CLI developed in Issue #108.

We should map the scraper to the `CatalogMetadata` model (or similar from csvwlib). This could then be directly passed to the Cube in a python script, or serialised to a `scraper.json` for use with the CLI in #108.

You should start making changes to the code in gss-utils.
- [x] Install the csv-qb package as a dependency in gss-utils
- [x] Alter the (gss-utils) scraper class with a new method which maps itself into a `CatalogMetadata` (in csvqb) model. ++ do some behave tests in gss-utils here.
- [x] Provide easy functionality to read/write the `CatalogMetadata` from/to JSON.
- [x] Augment the CLI from #108 so that it takes a `metadata-overrides` argument which specifies the location of the `CatalogMetadata` JSON file. It should load this data in and take it **in preference** to any configuration from the `info.json`. ++ alter the behave tests in the csvqb lib.

**Comment by robons** [comment]
I've spent some time today refactoring the gss-utils project to accept a more modern verison of rdflib (it was pinned at 4.2.2 - which is pretty old now)... https://github.com/GSS-Cogs/gss-utils/pull/316
