### ISSUE TITLE
Decide on appropriate python version

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#59]
We're currently making use of some functionality which [requires python 3.9 to be installed](https://www.python.org/dev/peps/pep-0593/). Is it okay to be using such a modern version of python?

- Which version of python are people typically using?
- Do users make use of tools like [pyenv](https://github.com/pyenv/pyenv) or conda to support multiple version of python at one?

**Comment by canwaf** [comment]
We're using python 3.9.
