### ISSUE TITLE
Unit Tests RDF Serialisation

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#75]
Serialisation of our RDF models can be triggered by creating an `rdflib.Graph` and passing it to the `model.to_graph(...)` method on the model.

```python
graph = rdflib.Graph()
model.to_graph(graph)
# you can now query `graph` as you would any RDF datastore.
```

- [x] Add Unit-test framework to sharedmodel package.
- [x] Test overriding of attributes in subclass - do we see the overriden triple outputted whilst the original triple is suppressed?
- [x] Test that `Resource[T]` is serialised properly for both ExistingResource and NewResource types (ensures recursive serialisation for NewResource types).
- [x] Test that circular `Resource[T]` references are serialised properly.
- [x] Test that multiple `Triple`s can be specified in an annotation. Ensure they both get serialised properly.
- [x] Test exceptions are raised when `PropertyStatus.mandatory` triples have no value provided when serializing, but `recommended`/`optional` silently pass where values haven't been provided.

**Comment by rossbowen** [comment]
`model` above refers to any subclass of [`sharedmodels.rdf.resource.RdfResource`](https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/sharedmodels/sharedmodels/rdf/resource.py#L13). Any subclass of `RdfResource` can be serialised into RDF.

https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/sharedmodels/sharedmodels/rdf/resource.py#L13

This is used when writing to CSVW - RDF-like classes are serialised into RDF and then output into JSON-LD.

https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/csvqb/csvqb/writers/qbwriter.py#L33

https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/csvqb/csvqb/writers/qbwriter.py#L89-L95
