### ISSUE TITLE
Serialise Unit and Attribute Values alongside qb:DSD in CSV-W

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvwlib#79]
Using abstract common model...

- Iterate through `NewQbAttributes`, `NewQbUnit`
- Serialise and add json to `RDFS:seeAlso` portion of the csvw.

(And tests)

**Comment by canwaf** [comment]
@robons to provide more detail here.

**Comment by robons** [comment]
Whoever picks this issue up, please talk to @robons to get the background understanding necessary.

**Comment by canwaf** [comment]
This one will be a group implementation.

**Comment by rossbowen** [comment]
As an example, there is a `QbMultiUnits` class with a `.from_data()` method:

https://github.com/GSS-Cogs/csvwlib/blob/main/csvqb/csvqb/models/cube/csvqb/components/unit.py#L74

If I have a CSV file with a column containing units, e.g. `my_units = ["people", "things"]`, calling `QbMultiUnits.from_data(my_units)` will give you a list `[NewQbUnit(label = "people"), NewQbUnit(label = "things")]`

https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/csvqb/csvqb/models/cube/csvqb/components/unit.py#L35

The information from those entries (their uris, labels etc.) need to be [added to the resulting CSVW](https://github.com/GSS-Cogs/csvwlib/blob/main/csvqb/csvqb/writers/qbwriter.py) - something along the lines of:

```jsonc
{
    //...
    "rdfs:seeAlso": [
        {
            "@id": "http://gss-data.org.uk/some-sensible-uri-for-attributes/people",
            "@type": "qb:AttributeProperty",
            "label": "people"
        },
        {
            "@id": "http://gss-data.org.uk/some-sensible-uri-for-attributes/things",
            "@type": "qb:AttributeProperty",
            "label": "things"
        }
    ]
}

```

**Comment by robons** [comment]
Before merging this PR, we'll have to retrofit the arbitrary RDF-serialisation functionality onto this model added in #29

**Comment by robons** [comment]
We should also serialise `NewQbAttributeValues` in this issue (done in #87).
