### ISSUE TITLE
QbAttribute refactoring & validation

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#87]
In a similar fashion to #83, we need to add a ValidationError when a user declares that a column is an `ExistingQbAttribute` without providing a `output_uri_template` mapping. Make sure you add a unit test to ensure this works.

Further, In #74 we considered adding a `qb:codeList` definition to attribute properties to allow us to infer the `output_uri_template` given the attribute's code-list; we will no longer being doing this. We therefore have a defunct [code_list attribute](https://github.com/GSS-Cogs/csvwlib/blob/ded06aac145c9ab55a470b5da89dadc307be7a37/csvqb/csvqb/models/cube/csvqb/components/attribute.py#L40) property on the class - **please remove this as part of this task**. Once this has been removed, **we will need a new way of being able to define new attribute values**. The `NewQbAttribute.from_data` method must be **updated** to generate `NewQbAttributeValue`s from the distinct values provided.

Make sure that you add a unit test to ensure that these `NewQbAttributeValue`s are correctly (and distinctly) created from existing data.

Blocks #79.

**Comment by CharlesRendle** [comment]
In review but Jenkins build is failing.
