### ISSUE TITLE
pytest migration

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvwlib#93]
@CharlesRendle has presented a few options in terms of unit test frameworks that we want to work with and has recommended that we go forwards with pytest.

This task it to create a PR which begins to migrate our existing unittest tests towards using the pytest no-class *pythonic* syntax.

- [x] Rename all test files using the `test_*.py` convention.
- [x] Migrate the following two test classes to the pytest *pythonic* way of testing (i.e. they should no longer be using the unittest framework & there should presumably be no classes in sight). 
  - [x] `csvqb.tests.unit.configloader.infojsontests`
  - [x] `csvqb.tests.unit.cube.qb.errorvalidation`
- [x] Ensure that there are equivalents for the more exotic assertions that we can make (e.g. ensuring two lists have the same elements but accept them in different orders like unittest's [assertCountEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual). We don't want to have to re-write a bunch of assertions which someone else has already written for us). **Let's see the PR at this stage to make sure we're happy**.
- [ ] Rework the `JenkinsFile` so that all tests are run using pytest.

At some point before completing this work, we also need to make sure that it's easy for us to run the tests in both PyCharm and VSCode.

**N.B. the place to install pytest (and remove unittest) is in our [devtools](https://github.com/GSS-Cogs/csvwlib/tree/main/devtools) package.**  You'll want to install/remove from there and then run `pipenv-setup sync` in the `devtools` environment. Once you've done that, you'll be able to run `pipenv lock --dev` in the downstream packages and the change will be propagated.

**Comment by canwaf** [comment]
Notes to self (further reading):
* https://stackoverflow.com/questions/24838948/how-can-i-convert-python-unittests-to-py-test-when-having-global-fixtures#24841254

**Comment by dannysepler** [comment]
Hey! I wrote a pip package to do this, and am now shamelessly searching for projects that need it 🙃 https://github.com/dannysepler/pytestify

I looked at your code, some things may not perfectly translate over. (Like I'm not sure how it'll do with your "UnitTestBase" class). But it may help?

**Comment by canwaf** [comment]
Hey @dannysepler, thanks for your contribution. I didn't end up using pytestify, because I'm leaning how to migrate tests as practise for writing them. That said, your list of asserts was incredibly helpful.

The two gaps as highlighted in the ticket (flagging @robons), were the more unique tests, these were checking if two lists were isomorphic. This is done by splitting up the two checks necessary.
```
assert len(listA) == len(listB)
assert set(listA) == set(listB)
```

And the only other one which stumped me was the catching a yote Exception, but the block below also gives us the Exception in the `exception` variable if we were bothered with the type of Exception.
```
with pytest.raises(Exception) as exception:

    def fetch_exception():
        qbwriter._get_default_property_value_uris_for_column(column)

fetch_exception()
```
